version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: landscaping_postgres_simple
    environment:
      POSTGRES_DB: landscaping_db
      POSTGRES_USER: landscaping_user  
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U landscaping_user -d landscaping_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: landscaping_redis_simple
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    image: nginx:alpine
    container_name: landscaping_web_simple
    ports:
      - "8081:80"
    volumes:
      - ./demo-web:/usr/share/nginx/html
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: