global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@landscaping-app.com'
  smtp_auth_username: 'alerts@landscaping-app.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m

    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m

    - match:
        alertname: ServiceDown
      receiver: 'service-down-alerts'
      group_wait: 5s
      repeat_interval: 2m

    - match_re:
        alertname: '(PostgreSQL|Redis).*'
      receiver: 'database-alerts'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'default'
    email_configs:
      - to: 'devops@landscaping-app.com'
        subject: '[ALERT] {{ .GroupLabels.alertname }} on {{ .GroupLabels.instance }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Status: {{ .Status }}
          {{ end }}
        headers:
          Priority: 'high'

  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@landscaping-app.com,oncall@landscaping-app.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }} - Immediate Action Required'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Service: {{ .Labels.job }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          Status: {{ .Status }}
          
          Runbook: https://runbook.landscaping-app.com/alerts/{{ .Labels.alertname }}
          {{ end }}
        headers:
          Priority: 'urgent'
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          🚨 **CRITICAL ALERT** 🚨
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Instance:** {{ .Labels.instance }}
          **Service:** {{ .Labels.job }}
          **Started:** {{ .StartsAt }}
          {{ end }}
        color: 'danger'
    
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: 'Critical Alert: {{ .GroupLabels.alertname }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@landscaping-app.com'
        subject: '[WARNING] {{ .GroupLabels.alertname }} on {{ .GroupLabels.instance }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Service: {{ .Labels.job }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          Status: {{ .Status }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: 'Warning Alert: {{ .GroupLabels.alertname }}'
        text: |
          ⚠️ **WARNING ALERT** ⚠️
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Instance:** {{ .Labels.instance }}
          **Service:** {{ .Labels.job }}
          **Started:** {{ .StartsAt }}
          {{ end }}
        color: 'warning'

  - name: 'service-down-alerts'
    email_configs:
      - to: 'devops@landscaping-app.com,oncall@landscaping-app.com'
        subject: '[SERVICE DOWN] {{ .GroupLabels.job }} is DOWN'
        body: |
          🔴 SERVICE DOWN 🔴
          
          {{ range .Alerts }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          
          This requires immediate attention!
          {{ end }}
        headers:
          Priority: 'urgent'
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'SERVICE DOWN: {{ .GroupLabels.job }}'
        text: |
          🔴 **SERVICE DOWN** 🔴
          {{ range .Alerts }}
          **Service:** {{ .Labels.job }}
          **Instance:** {{ .Labels.instance }}
          **Description:** {{ .Annotations.description }}
          **Started:** {{ .StartsAt }}
          
          🚨 **IMMEDIATE ACTION REQUIRED** 🚨
          {{ end }}
        color: 'danger'
    
    webhook_configs:
      - url: 'https://api.landscaping-app.com/webhooks/alert'
        http_config:
          bearer_token: '${WEBHOOK_TOKEN}'

  - name: 'database-alerts'
    email_configs:
      - to: 'database-team@landscaping-app.com,devops@landscaping-app.com'
        subject: '[DATABASE] {{ .GroupLabels.alertname }} Alert'
        body: |
          🗄️ DATABASE ALERT 🗄️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          Status: {{ .Status }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database-alerts'
        title: 'Database Alert: {{ .GroupLabels.alertname }}'
        text: |
          🗄️ **DATABASE ALERT** 🗄️
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Database:** {{ .Labels.job }}
          **Instance:** {{ .Labels.instance }}
          **Severity:** {{ .Labels.severity }}
          **Started:** {{ .StartsAt }}
          {{ end }}
        color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'